### ISSUE TITLE
Add support for WRITE operations

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-php#70]
### What

- Add support for WRITE operations
```[tasklist]
### Tasks
- [ ] Allow to Save product to Open Food Facts
- [ ] Add support for Sending images
- [ ] Add support for User comments and auth
- [ ] Add support for Anonymous photo upload
- [ ] Add support for Photo operations (rotate, crop, select, unselect with language awareness)
```
